In [2]:
import tensorflow as tf
from function import showOperation as showOp

In [3]:
showOp(tf.zeros([2,3]))                     # [[ 0.  0.  0.] [ 0.  0.  0.]]
showOp(tf.ones([2,3], tf.int32))            # [[1 1 1] [1 1 1]]
showOp(tf.zeros_like(tf.ones([2,3])))       # [[ 0.  0.  0.] [ 0.  0.  0.]]
showOp(tf.fill([2,3], 2))                   # [[2 2 2] [2 2 2]]
showOp(tf.fill([2,3], 2.0))                 # [[ 2.  2.  2.] [ 2.  2.  2.]]

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[1 1 1]
 [1 1 1]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[2 2 2]
 [2 2 2]]
[[ 2.  2.  2.]
 [ 2.  2.  2.]]


In [7]:
for i in xrange(50) :
    showOp(tf.random_uniform([1], -0.1, 1.0))

[ 0.71717125]
[ 0.64725435]
[ 0.44438657]
[ 0.93502581]
[ 0.67023867]
[ 0.53889161]
[ 0.50460052]
[ 0.01361922]
[ 0.93308592]
[ 0.92811656]
[ 0.33393142]
[ 0.22383317]
[ 0.28904253]
[ 0.45345703]
[ 0.95190728]
[ 0.71492934]
[ 0.91338205]
[ 0.50887078]
[ 0.75714409]
[ 0.14750803]
[ 0.52661085]
[ 0.62576956]
[ 0.86462355]
[ 0.39519152]
[-0.04515807]
[ 0.44264939]
[ 0.6493144]
[ 0.93357849]
[ 0.41148707]
[ 0.5977971]
[ 0.51787484]
[-0.08949516]
[ 0.70773751]
[ 0.34351665]
[-0.0769738]
[ 0.63011742]
[ 0.78084481]
[ 0.52187389]
[-0.08720051]
[ 0.02853633]
[ 0.82458961]
[ 0.99282801]
[ 0.3274368]
[ 0.15307581]
[ 0.09127978]
[ 0.15510127]
[ 0.76495653]
[ 0.0467949]
[ 0.11473518]
[ 0.31734595]


In [8]:
showOp(tf.zeros([1]))

[ 0.]
